### ISSUE TITLE
Questions about SQL

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npc-talent-template#15]
Can someone explain to me why:

- the data is put in the `characters` database ? and not in world ?
- what does each table represent, example: `template_npc_alliance` ?? `template_npc_human` ??? Why so many tables ?

**Comment by mindsear** [comment]
1. My reason is saying The data was appropriate for 'characters' database because 'characters' database holds character data. But I understand why you asked that question, because we're dealing primarily with an NPC and its data and not characters.

2. I do agree, it's confusing and certainly, useless. Those two tables could be merged and a new column can be added to template_npc_alliance in order to check the race.

Many more things should be changed to this module, because, as we all know it's pretty bugged.
Unfortunately, I have other priorities in life right now. I apologize that I am unable to deal with this.

**Comment by BarbzYHOOL** [comment]
Yes, thank you for explaining, I just wanted to know the reasons. I might be able to change it to at least use the correct database (world).

So what is the difference between template_npc_alliance  and template_npc_horde ? There is probably a good reason

It's pretty bugged? damnit, it's one of those very useful module though

**Comment by mindsear** [comment]
I assume you meant to ask what's the difference between **template_npc_alliance** and **template_npc_human**.

The only difference is that **template_npc_human** is used to check for human race, other than that they're are the same tables holding the same data. 
I reckon, the creator of this script didn't know how to check for human race in a useful manner. And this could be done just by adding a simple column to **template_npc_alliance** and modify the script accordingly. No need for another table to check for human race.

**Comment by BarbzYHOOL** [comment]
Why a special case for alliance vs horde ? After a quick check, I suppose it's because item sets are different for both factions (note: i didn't test the module for a long time and will do soon)

But why a special case for humans ?

**Comment by mindsear** [comment]
Hmm.. I guess I was wrong when I said that  **template_npc_alliance** and **template_npc_human** are the same tables holding the same data.

After a quick look I found out they have some slight differences when it comes to gear, especially trinkets. 
For example, Human Rogue using Assassination spec, has a different trinket [(Dark Matter)](https://wotlk.evowow.com/?item=46038) than other race rogue using assassination spec [(Medallion of the Alliance)](https://wotlk.evowow.com/?item=51377).

![](https://i.ibb.co/Yth6WPD/000-1.png)

This is the reason the creator of this script made two separate tables. He thought human race doesn't need [Medallion of the Alliance](https://wotlk.evowow.com/?item=51377) because they have the racial spell [Every Man for Himself](https://wotlk.evowow.com/?spell=59752).

**Comment by BarbzYHOOL** [comment]
ah ok thank you, i miss that knowledge of the game so that's why I asked

I guess the script and the SQL just need a refactor then

**Comment by pangolp** [comment]
I'm going to close this pull request, because it's from the year 2020. Please, if you think I'm wrong and the issue you're talking about still persists, let me know and we'll deal with it again. I want to try to keep the repository clean and wait for new issues or pull requests.
